### ISSUE TITLE
无法在字符串中使用

### ISSUE THREAD

**Issue by shoucandanghehe** [liwh011/vscode-pinyin-ime#2]

**Comment by liwh011** [comment]
这个行为是符合预期的。
这个插件的原理是在编辑器触发补全时向其中插入补全项（候选词）。至于何时触发补全，这个时机似乎与语言的LSP有关，并且大多数语言都不支持字符串补全，因此本插件无法在字符串中使用。
不知道有没有别的更好的API可以实现这个功能

**Comment by shoucandanghehe** [comment]
> 不知道有没有别的更好的API可以实现这个功能

应该是有的
比如Python的Literal类型就可以提供字符串补全
![image](https://github.com/liwh011/vscode-pinyin-ime/assets/51957264/72dbe5ad-a2b6-4c26-a28d-4f9e3202b722)

**Comment by liwh011** [comment]
> > 不知道有没有别的更好的API可以实现这个功能
> 
> 应该是有的 比如Python的Literal类型就可以提供字符串补全 ![image](https://user-images.githubusercontent.com/51957264/252128613-72dbe5ad-a2b6-4c26-a28d-4f9e3202b722.png)


在vsc设置当中把`editor.quickSuggestions`中的`strings`和`comments`两项改为开启，就可以在字符串和注释当中使用了。
不过需要注意的是，除了在“用户”选项卡修改这一项以外，也要留意一下“工作区”选项卡中的这个设置项是否也修改了。是否生效以工作区下的设置为准。
![图片](https://github.com/liwh011/vscode-pinyin-ime/assets/58688853/b641408b-10a6-4b61-b1eb-e1e623734b01)
![图片](https://github.com/liwh011/vscode-pinyin-ime/assets/58688853/5192d537-eba9-49f9-b2b3-b129cfd5a70f)
